#!/bin/bash
rm -r build && mkdir build && cd build && cmake .. && make -j16 && PYTHONPATH=./src/ python ../scripts/test_pyinterf.py && cd ..
#cd build && make clean && cmake .. && make -j16 && PYTHONPATH=./src/ python ../scripts/test_pyinterf.py && cd ..
